# Generated by Django 5.2 on 2025-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCPGHLContactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcp_customer_id', models.CharField(max_length=255, unique=True)),
                ('ghl_contact_id', models.CharField(max_length=255)),
                ('hcp_email', models.EmailField(max_length=254)),
                ('ghl_location_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HCPGHLOpportunityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcp_estimate_id', models.CharField(max_length=255, unique=True)),
                ('hcp_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_opportunity_id', models.CharField(max_length=255)),
                ('ghl_contact_id', models.CharField(max_length=255)),
                ('ghl_location_id', models.CharField(max_length=255)),
                ('hcp_estimate_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
