# Generated by Django 5.2 on 2025-06-04 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hcpghlcontactmapping_hcpghlopportunitymapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcp_customer_id', models.CharField(max_length=255)),
                ('ghl_contact_id', models.CharField(max_length=255)),
                ('hcp_company_id', models.CharField(max_length=255)),
                ('ghl_location_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('hcp_customer_id', 'hcp_company_id')},
            },
        ),
        migrations.CreateModel(
            name='HCPToGHLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcp_company_id', models.CharField(max_length=255, unique=True)),
                ('ghl_location_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ghl_credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ghlauthcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcp_estimate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hcp_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_opportunity_id', models.CharField(max_length=255)),
                ('hcp_company_id', models.CharField(max_length=255)),
                ('ghl_location_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('hcp_estimate_id', 'hcp_company_id')},
            },
        ),
        migrations.DeleteModel(
            name='HCPGHLContactMapping',
        ),
        migrations.DeleteModel(
            name='HCPGHLOpportunityMapping',
        ),
    ]
